In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
df1 = pd.read_excel("case_study1.xlsx")
df2 = pd.read_excel("case_study2.xlsx")

In [4]:
df1.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,Tot_TL_closed_L12M,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,Auto_TL,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,0,0,0.00,0.0,0,0,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,1,0,1.00,0.0,0,0,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,2,0,0.25,0.0,1,1,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,1,0,1.00,0.0,1,0,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,0,0,0.00,0.0,0,1,0,0,0,0,0,3,0,2,131,32

In [5]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,max_deliq_6mts,max_deliq_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,num_std_6mts,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_6mts,num_dbt_12mts,num_lss,num_lss_6mts,num_lss_12mts,recent_level_of_deliq,tot_enq,CC_enq,CC_enq_L6m,CC_enq_L12m,PL_enq,PL_enq_L6m,PL_enq_L12m,time_since_recent_enq,enq_L12m,enq_L6m,enq_L3m,MARITALSTATUS,EDUCATION,AGE,GENDER,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_of_active_TLs_ever,pct_opened_TLs_L6m_of_L12m,pct_currentBal_all_TL,CC_utilization,CC_Flag,PL_utilization,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,-99999,-99999,0,0,21,5,11,0,0,0,0,0,0,0,0,0,29,6,0,0,0,6,0,0,566,0,0,0,Married,12TH,48,M,51000,114,0.200,0.0,0.798,-99999.0,0,0.798,1,0.0,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,209,1,0,0,Single,GRADUATE,23,F,19000,50,1.000,0.0,0.370,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,25,25,0,0,10,5,10,0,0,0,0,0,0,0,0,0,25,4,0,0,0,0,0,0,587,0,0,0,Married,SSC,40,M,18,191,1.000,0.5,0.585,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,-99999,-99999,0,0,5,4,5,0,0,0,0,0,0,0,0,0,0,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,Married,SSC,34,M,10000,246,1.000,1.0,0.990,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,-99999,-99999,0,0,53,4,16,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3951,0,0,0,Married,POST-GRADUATE,48,M,15000,75,0.333,0.0,0.000,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PROSPECTID            51336 non-null  int64
 1   Total_TL              51336 non-null  int64
 2   Tot_Closed_TL         51336 non-null  int64
 3   Tot_Active_TL         51336 non-null  int64
 4   Total_TL_opened_L6M   51336 non-null  int64
 5   Tot_TL_closed_L6M     51336 non-null  int64
 6   pct_tl_open_L6M       51336 non-null  float64
 7   pct_tl_closed_L6M     51336 non-null  float64
 8   pct_active_tl         51336 non-null  float64
 9   pct_closed_tl         51336 non-null  float64
 10  Total_TL_opened_L12M  51336 non-null  int64
 11  Tot_TL_closed_L12M    51336 non-null  int64
 12  pct_tl_open_L12M      51336 non-null  float64
 13  pct_tl_closed_L12M    51336 non-null  float64
 14  Tot_Missed_Pmnt       51336 non-null  int64
 15  Auto_TL               51336 non-null  int64
 16  CC_TL                 51336 non-null  int64
 17  Consumer_TL           51336 non-null  int64
 18  Gold_TL               51336 non-null  int64
 19  Home_TL               51336 non-null  int64
 20  PL_TL                 51336 non-null  int64
 21  Secured_TL            51336 non-null  int64
 22  Unsecured_TL          51336 non-null  int64
 23  Other_TL              51336 non-null  int64
 24  Age_Oldest_TL         51336 non-null  int64
 25  Age_Newest_TL         51336 non-null  int64
dtypes: float64(6), int64(20)
memory usage: 10.2 MB

In [7]:
print(df1.shape)
print(df2.shape)

(51336, 26)
(51336, 62)

## Data Cleaning

In [9]:
df1 = df1[df1['Age_Oldest_TL'] != -99999]

In [10]:
df1.shape

(51296, 26)

In [11]:
columns_to_removed = []

In [12]:
for i in df2.columns:
    count = (df2[i] == -99999).sum()
    percentage =round((count/len(df2))*100)
    if count>0:
        print(f'columns {i},count {count},percentage {percentage}')

columns time_since_recent_payment,count 4291,percentage 8
columns time_since_first_deliquency,count 35949,percentage 70
columns time_since_recent_deliquency,count 35949,percentage 70
columns max_delinquency_level,count 35949,percentage 70
columns max_deliq_6mts,count 12890,percentage 25
columns max_deliq_12mts,count 10832,percentage 21
columns tot_enq,count 6321,percentage 12
columns CC_enq,count 6321,percentage 12
columns CC_enq_L6m,count 6321,percentage 12
columns CC_enq_L12m,count 6321,percentage 12
columns PL_enq,count 6321,percentage 12
columns PL_enq_L6m,count 6321,percentage 12
columns PL_enq_L12m,count 6321,percentage 12
columns time_since_recent_enq,count 6321,percentage 12
columns enq_L12m,count 6321,percentage 12
columns enq_L6m,count 6321,percentage 12
columns enq_L3m,count 6321,percentage 12
columns pct_currentBal_all_TL,count 72,percentage 0
columns CC_utilization,count 47636,percentage 93
columns PL_utilization,count 44435,percentage 87
columns max_unsec_exposure_inPct,count 23178,percentage 45

In [13]:
for i in df2.columns:
    if (df2[i] == -99999).sum() > 10000:
        columns_to_removed.append(i)
        print(i)

time_since_first_deliquency
time_since_recent_deliquency
max_delinquency_level
max_deliq_6mts
max_deliq_12mts
CC_utilization
PL_utilization
max_unsec_exposure_inPct

In [14]:
columns_to_removed

['time_since_first_deliquency',
 'time_since_recent_deliquency',
 'max_delinquency_level',
 'max_deliq_6mts',
 'max_deliq_12mts',
 'CC_utilization',
 'PL_utilization',
 'max_unsec_exposure_inPct']

In [15]:
df2 = df2.drop(columns=columns_to_removed)

In [16]:
df2.shape

(51336, 54)

In [17]:
common_columns = []

for col in df1.columns:
    if col in df2.columns:
        common_columns.append(col)

print(common_columns)

['PROSPECTID']

In [18]:
df = pd.merge(df1,df2,on='PROSPECTID',how='inner')
df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,Tot_TL_closed_L12M,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,Auto_TL,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,num_std_6mts,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_6mts,num_dbt_12mts,num_lss,num_lss_6mts,num_lss_12mts,recent_level_of_deliq,tot_enq,CC_enq,CC_enq_L6m,CC_enq_L12m,PL_enq,PL_enq_L6m,PL_enq_L12m,time_since_recent_enq,enq_L12m,enq_L6m,enq_L3m,MARITALSTATUS,EDUCATION,AGE,GENDER,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_of_active_TLs_ever,pct_opened_TLs_L6m_of_L12m,pct_currentBal_all_TL,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,0,0,0.00,0.0,0,0,0,0,1,0,4,1,4,0,72,18,549,11,29,0,0,0,0,0,21,5,11,0,0,0,0,0,0,0,0,0,29,6,0,0,0,6,0,0,566,0,0,0,Married,12TH,48,M,51000,114,0.200,0.0,0.798,0,1,0.0,0.0,0.0,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,1,0,1.00,0.0,0,0,0,1,0,0,0,0,1,0,7,7,47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,209,1,0,0,Single,GRADUATE,23,F,19000,50,1.000,0.0,0.370,0,0,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,2,0,0.25,0.0,1,1,0,6,1,0,0,2,6,0,47,2,302,9,25,1,9,8,0,0,10,5,10,0,0,0,0,0,0,0,0,0,25,4,0,0,0,0,0,0,587,0,0,0,Married,SSC,40,M,18,191,1.000,0.5,0.585,0,0,0.0,0.0,0.0,0.0,1,0,ConsumerLoan,others,693,P2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,1,0,1.00,0.0,1,0,0,0,0,0,0,0,1,1,5,5,-99999,0,0,0,0,0,0,0,5,4,5,0,0,0,0,0,0,0,0,0,0,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,Married,SSC,34,M,10000,246,1.000,1.0,0.990,0,0,0.0,0.0,0.0,0.0,0,0,others,others,673,P2
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,0,0,0.00,0.0,0,1,0,0,0,0,0,3,0,2,131,32,583,0,0,0,0,0,0,0,53,4,16,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3951,0,0,0,Married,POST-GRADUATE,48,M,15000,75,0.333,0.0,0.000,0,0,0.0,0.0,0.0,0.0,0,0,AL,AL,753,P1

In [19]:
df.shape

(51296, 79)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51296 entries, 0 to 51295
Data columns (total 79 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROSPECTID                  51296 non-null  int64
 1   Total_TL                    51296 non-null  int64
 2   Tot_Closed_TL               51296 non-null  int64
 3   Tot_Active_TL               51296 non-null  int64
 4   Total_TL_opened_L6M         51296 non-null  int64
 5   Tot_TL_closed_L6M           51296 non-null  int64
 6   pct_tl_open_L6M             51296 non-null  float64
 7   pct_tl_closed_L6M           51296 non-null  float64
 8   pct_active_tl               51296 non-null  float64
 9   pct_closed_tl               51296 non-null  float64
 10  Total_TL_opened_L12M        51296 non-null  int64
 11  Tot_TL_closed_L12M          51296 non-null  int64
 12  pct_tl_open_L12M            51296 non-null  float64
 13  pct_tl_closed_L12M          51296 non-null  float64
 14  Tot_Missed_Pmnt             51296 non-null  int64
 15  Auto_TL                     51296 non-null  int64
 16  CC_TL                       51296 non-null  int64
 17  Consumer_TL                 51296 non-null  int64
 18  Gold_TL                     51296 non-null  int64
 19  Home_TL                     51296 non-null  int64
 20  PL_TL                       51296 non-null  int64
 21  Secured_TL                  51296 non-null  int64
 22  Unsecured_TL                51296 non-null  int64
 23  Other_TL                    51296 non-null  int64
 24  Age_Oldest_TL               51296 non-null  int64
 25  Age_Newest_TL               51296 non-null  int64
 26  time_since_recent_payment   51296 non-null  int64
 27  num_times_delinquent        51296 non-null  int64
 28  max_recent_level_of_deliq   51296 non-null  int64
 29  num_deliq_6mts              51296 non-null  int64
 30  num_deliq_12mts             51296 non-null  int64
 31  num_deliq_6_12mts           51296 non-null  int64
 32  num_times_30p_dpd           51296 non-null  int64
 33  num_times_60p_dpd           51296 non-null  int64
 34  num_std                     51296 non-null  int64
 35  num_std_6mts                51296 non-null  int64
 36  num_std_12mts               51296 non-null  int64
 37  num_sub                     51296 non-null  int64
 38  num_sub_6mts                51296 non-null  int64
 39  num_sub_12mts               51296 non-null  int64
 40  num_dbt                     51296 non-null  int64
 41  num_dbt_6mts                51296 non-null  int64
 42  num_dbt_12mts               51296 non-null  int64
 43  num_lss                     51296 non-null  int64
 44  num_lss_6mts                51296 non-null  int64
 45  num_lss_12mts               51296 non-null  int64
 46  recent_level_of_deliq       51296 non-null  int64
 47  tot_enq                     51296 non-null  int64
 48  CC_enq                      51296 non-null  int64
 49  CC_enq_L6m                  51296 non-null  int64
 50  CC_enq_L12m                 51296 non-null  int64
 51  PL_enq                      51296 non-null  int64
 52  PL_enq_L6m                  51296 non-null  int64
 53  PL_enq_L12m                 51296 non-null  int64
 54  time_since_recent_enq       51296 non-null  int64
 55  enq_L12m                    51296 non-null  int64
 56  enq_L6m                     51296 non-null  int64
 57  enq_L3m                     51296 non-null  int64
 58  MARITALSTATUS               51296 non-null  object
 59  EDUCATION                   51296 non-null  object
 60  AGE                         51296 non-null  int64
 61  GENDER                      51296 non-null  object
 62  NETMONTHLYINCOME            51296 non-null  int64
 63  Time_With_Curr_Empr         51296 non-null  int64
 64  pct_of_active_TLs_ever      51296 non-null  float64
 65  pct_opened_TLs_L6m_of_L12m  51296 non-null  float64
 66  pct_currentBal_all_TL       51296 non-null  float64
 67  CC_Flag                     51296 non-null  int64
 68  PL_Flag                     51296 non-null  int64
 69  pct_PL_enq_L6m_of_L12m      51296 non-null  float64
 70  pct_CC_enq_L6m_of_L12m      51296 non-null  float64
 71  pct_PL_enq_L6m_of_ever      51296 non-null  float64
 72  pct_CC_enq_L6m_of_ever      51296 non-null  float64
 73  HL_Flag                     51296 non-null  int64
 74  GL_Flag                     51296 non-null  int64
 75  last_prod_enq2              51296 non-null  object
 76  first_prod_enq2             51296 non-null  object
 77  Credit_Score                51296 non-null  int64
 78  Approved_Flag               51296 non-null  object
dtypes: float64(13), int64(60), object(6)
memory usage: 30.9+ MB

In [21]:
# To find categorical columns 
for i in df.columns:
    if df[i].dtypes == 'object':
        print(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [22]:
#Check weather categorical columns are having some impacvt or not - Hypothesis Testing

## Feature Selection

In [24]:
df.MARITALSTATUS.value_counts()

MARITALSTATUS
Married    37724
Single     13572
Name: count, dtype: int64

In [25]:
df.EDUCATION.value_counts()

EDUCATION
GRADUATE          16655
12TH              14458
SSC                9268
UNDER GRADUATE     5491
OTHERS             2915
POST-GRADUATE      2240
PROFESSIONAL        269
Name: count, dtype: int64

In [26]:
df.GENDER.value_counts()

GENDER
M    45211
F     6085
Name: count, dtype: int64

In [27]:
df.MARITALSTATUS.value_counts()

MARITALSTATUS
Married    37724
Single     13572
Name: count, dtype: int64

In [28]:
df.Approved_Flag.value_counts()

Approved_Flag
P2    32162
P3     7449
P4     5882
P1     5803
Name: count, dtype: int64

In [29]:
df.first_prod_enq2.value_counts()

first_prod_enq2
others          28095
ConsumerLoan    11852
PL               4885
AL               2869
CC               2187
HL               1408
Name: count, dtype: int64

In [30]:
df.last_prod_enq2.value_counts()

last_prod_enq2
others          20808
ConsumerLoan    17782
PL               7955
CC               2338
AL               1511
HL                902
Name: count, dtype: int64

## Hypothesis Testing

**Chi-Squared Test**
To check whether the categorical features are associated with output feature or not. It means whether we can keep categorical feature or we should remove it

### Hypothesis Testing for Feature Selection

For each categorical feature, we define the hypotheses as follows:

#### Null Hypothesis (H0):
There is **no relationship** between the feature and the target variable (they are independent).  
- The feature **does not influence** the target.
- It **should be removed** if (H0) is true.
- 
#### Alternative Hypothesis (H1):
There **is a relationship** between the feature and the target variable (they are dependent).  
- The feature **affects** the target.
- It **should be kept** if (H0) is rejected.

In [64]:
import pandas as pd
from scipy.stats import chi2_contingency

for i in ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
    chi2, pval, dof, expected = chi2_contingency(pd.crosstab(df[i], df['Approved_Flag']))
    print(i, '---', pval)

MARITALSTATUS --- 2.7347247145640217e-257
EDUCATION --- 6.772122013692765e-38
GENDER --- 0.000259241464445085
last_prod_enq2 --- 0.0
first_prod_enq2 --- 0.0

In [68]:
import numpy as np
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Selecting numerical features
numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()
vif_data = df[numeric_columns].copy()

# Set VIF threshold
vif_threshold = 6
columns_to_be_kept = []

while True:
    vif_values = [variance_inflation_factor(vif_data.values, i) for i in range(vif_data.shape[1])]
    vif_df = pd.DataFrame({"Feature": vif_data.columns, "VIF": vif_values})
    
    # Print VIF values
    print(vif_df.sort_values(by="VIF", ascending=False))
    
    max_vif = vif_df["VIF"].max()
    
    if max_vif < vif_threshold:
        break  # Stop if all VIFs are below threshold
    
    # Drop feature with highest VIF
    drop_feature = vif_df.loc[vif_df["VIF"] == max_vif, "Feature"].values[0]
    print(f"Dropping {drop_feature} with VIF: {max_vif}")
    vif_data.drop(columns=[drop_feature], inplace=True)

# Store final features with low VIF
columns_to_be_kept = vif_data.columns.tolist()

print("\nFinal Features with Low VIF:\n", columns_to_be_kept)

C:\Users\my msi\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

                      Feature       VIF
31          num_deliq_6_12mts       inf
23                   Other_TL       inf
19                    Home_TL       inf
18                    Gold_TL       inf
17                Consumer_TL       inf
..                        ...       ...
60        Time_With_Curr_Empr  1.265841
26  time_since_recent_payment  1.230058
59           NETMONTHLYINCOME  1.055621
63      pct_currentBal_all_TL  1.005981
0                  PROSPECTID  1.001322

[73 rows x 2 columns]
Dropping Total_TL with VIF: inf

C:\Users\my msi\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

                      Feature       VIF
28             num_deliq_6mts       inf
60     pct_of_active_TLs_ever       inf
21               Unsecured_TL       inf
20                 Secured_TL       inf
19                      PL_TL       inf
..                        ...       ...
59        Time_With_Curr_Empr  1.265841
25  time_since_recent_payment  1.230058
58           NETMONTHLYINCOME  1.055621
62      pct_currentBal_all_TL  1.005981
0                  PROSPECTID  1.001322

[72 rows x 2 columns]
Dropping Tot_Closed_TL with VIF: inf

C:\Users\my msi\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

                      Feature       VIF
20               Unsecured_TL       inf
18                      PL_TL       inf
16                    Gold_TL       inf
15                Consumer_TL       inf
14                      CC_TL       inf
..                        ...       ...
58        Time_With_Curr_Empr  1.265841
24  time_since_recent_payment  1.230058
57           NETMONTHLYINCOME  1.055621
61      pct_currentBal_all_TL  1.005981
0                  PROSPECTID  1.001322

[71 rows x 2 columns]
Dropping pct_active_tl with VIF: inf

C:\Users\my msi\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

                      Feature       VIF
27            num_deliq_12mts       inf
26             num_deliq_6mts       inf
17                      PL_TL       inf
16                    Home_TL       inf
15                    Gold_TL       inf
..                        ...       ...
67                    HL_Flag  2.460556
37                    num_dbt  2.196945
34                    num_sub  1.568406
23  time_since_recent_payment  1.334693
60      pct_currentBal_all_TL  1.007339

[70 rows x 2 columns]
Dropping Auto_TL with VIF: inf

C:\Users\my msi\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

                      Feature           VIF
27          num_deliq_6_12mts           inf
25             num_deliq_6mts           inf
26            num_deliq_12mts           inf
46                CC_enq_L12m  1.494879e+10
45                 CC_enq_L6m  1.284645e+10
..                        ...           ...
66                    HL_Flag  2.460556e+00
36                    num_dbt  2.196945e+00
33                    num_sub  1.568406e+00
22  time_since_recent_payment  1.334693e+00
59      pct_currentBal_all_TL  1.007339e+00

[69 rows x 2 columns]
Dropping num_deliq_6mts with VIF: inf
                      Feature           VIF
45                CC_enq_L12m  1.494879e+10
44                 CC_enq_L6m  1.284645e+10
47                 PL_enq_L6m  8.089596e+09
48                PL_enq_L12m  7.294431e+09
43                     CC_enq  3.621386e+09
..                        ...           ...
65                    HL_Flag  2.460556e+00
35                    num_dbt  2.196945e+00
32                    num_sub  1.568406e+00
22  time_since_recent_payment  1.334693e+00
58      pct_currentBal_all_TL  1.007339e+00

[68 rows x 2 columns]
Dropping CC_enq_L12m with VIF: 14948790289.627014
                      Feature           VIF
46                 PL_enq_L6m  8.085544e+09
47                PL_enq_L12m  7.241282e+09
44                 CC_enq_L6m  4.765636e+09
50                    enq_L6m  2.762552e+09
45                     PL_enq  2.364471e+09
..                        ...           ...
64                    HL_Flag  2.460517e+00
35                    num_dbt  2.196714e+00
32                    num_sub  1.568370e+00
22  time_since_recent_payment  1.334631e+00
57      pct_currentBal_all_TL  1.007335e+00

[67 rows x 2 columns]
Dropping PL_enq_L6m with VIF: 8085544238.125538
                      Feature           VIF
44                 CC_enq_L6m  4.133624e+09
46                PL_enq_L12m  3.782556e+09
45                     PL_enq  2.363969e+09
43                     CC_enq  2.197539e+09
49                    enq_L6m  2.197233e+09
..                        ...           ...
63                    HL_Flag  2.460516e+00
35                    num_dbt  2.196615e+00
32                    num_sub  1.568345e+00
22  time_since_recent_payment  1.334624e+00
56      pct_currentBal_all_TL  1.007335e+00

[66 rows x 2 columns]
Dropping CC_enq_L6m with VIF: 4133623765.833348
                      Feature           VIF
45                PL_enq_L12m  3.519992e+09
44                     PL_enq  2.363968e+09
48                    enq_L6m  2.161721e+09
49                    enq_L3m  1.612558e+09
47                   enq_L12m  1.318978e+09
..                        ...           ...
62                    HL_Flag  2.460422e+00
35                    num_dbt  2.196203e+00
32                    num_sub  1.568292e+00
22  time_since_recent_payment  1.334315e+00
55      pct_currentBal_all_TL  1.007327e+00

[65 rows x 2 columns]
Dropping PL_enq_L12m with VIF: 3519992330.494837
                      Feature           VIF
47                    enq_L6m  2.158644e+09
48                    enq_L3m  1.603074e+09
46                   enq_L12m  1.156992e+09
43                     CC_enq  7.439458e+08
44                     PL_enq  6.408531e+08
..                        ...           ...
61                    HL_Flag  2.458122e+00
35                    num_dbt  2.196182e+00
32                    num_sub  1.568167e+00
22  time_since_recent_payment  1.334298e+00
54      pct_currentBal_all_TL  1.007323e+00

[64 rows x 2 columns]
Dropping enq_L6m with VIF: 2158643551.231838
                      Feature           VIF
47                    enq_L3m  8.922939e+08
43                     CC_enq  7.393489e+08
46                   enq_L12m  6.699743e+08
44                     PL_enq  6.401580e+08
42                    tot_enq  2.964263e+08
..                        ...           ...
60                    HL_Flag  2.458082e+00
35                    num_dbt  2.196159e+00
32                    num_sub  1.568062e+00
22  time_since_recent_payment  1.334243e+00
53      pct_currentBal_all_TL  1.007321e+00

[63 rows x 2 columns]
Dropping enq_L3m with VIF: 892293904.9007311
                      Feature           VIF
44                     PL_enq  5.903184e+08
46                   enq_L12m  5.204888e+08
43                     CC_enq  4.955119e+08
42                    tot_enq  2.710970e+08
45      time_since_recent_enq  9.629935e+03
..                        ...           ...
59                    HL_Flag  2.457062e+00
35                    num_dbt  2.196143e+00
32                    num_sub  1.568010e+00
22  time_since_recent_payment  1.333210e+00
52      pct_currentBal_all_TL  1.007314e+00

[62 rows x 2 columns]
Dropping PL_enq with VIF: 590318444.7357626
                      Feature           VIF
45                   enq_L12m  4.839013e+08
42                    tot_enq  2.691342e+08
43                     CC_enq  2.118429e+08
44      time_since_recent_enq  9.612512e+03
60               Credit_Score  4.072220e+03
..                        ...           ...
58                    HL_Flag  2.456214e+00
35                    num_dbt  2.195988e+00
32                    num_sub  1.567923e+00
22  time_since_recent_payment  1.333182e+00
51      pct_currentBal_all_TL  1.007306e+00

[61 rows x 2 columns]
Dropping enq_L12m with VIF: 483901342.3299811
                       Feature           VIF
43                      CC_enq  1.178339e+08
42                     tot_enq  1.177814e+08
44       time_since_recent_enq  9.612094e+03
59                Credit_Score  3.788238e+03
48      pct_of_active_TLs_ever  1.779460e+03
6                pct_closed_tl  1.201185e+03
17                  Secured_TL  8.920654e+01
14                     Gold_TL  5.828209e+01
18                Unsecured_TL  4.927647e+01
31               num_std_12mts  2.602404e+01
45                         AGE  2.193256e+01
7         Total_TL_opened_L12M  2.154044e+01
53      pct_PL_enq_L6m_of_L12m  2.140289e+01
13                 Consumer_TL  2.125885e+01
55      pct_PL_enq_L6m_of_ever  2.042514e+01
1                Tot_Active_TL  1.987370e+01
30                num_std_6mts  1.672219e+01
54      pct_CC_enq_L6m_of_L12m  1.642444e+01
56      pct_CC_enq_L6m_of_ever  1.562105e+01
27           num_times_30p_dpd  1.451937e+01
19                    Other_TL  1.387012e+01
8           Tot_TL_closed_L12M  1.109962e+01
2          Total_TL_opened_L6M  1.058313e+01
37               num_dbt_12mts  9.302441e+00
28           num_times_60p_dpd  8.466010e+00
49  pct_opened_TLs_L6m_of_L12m  8.313749e+00
25             num_deliq_12mts  8.185515e+00
23        num_times_delinquent  8.136897e+00
3            Tot_TL_closed_L6M  7.980789e+00
40               num_lss_12mts  7.950713e+00
9             pct_tl_open_L12M  7.906015e+00
4              pct_tl_open_L6M  7.792150e+00
20               Age_Oldest_TL  7.681057e+00
36                num_dbt_6mts  7.384550e+00
29                     num_std  7.248568e+00
26           num_deliq_6_12mts  6.929047e+00
39                num_lss_6mts  6.355633e+00
10          pct_tl_closed_L12M  6.120407e+00
24   max_recent_level_of_deliq  5.405576e+00
41       recent_level_of_deliq  4.972835e+00
16                       PL_TL  4.938988e+00
5            pct_tl_closed_L6M  4.781709e+00
15                     Home_TL  4.622610e+00
58                     GL_Flag  4.409850e+00
0                   PROSPECTID  4.004267e+00
47         Time_With_Curr_Empr  3.947366e+00
12                       CC_TL  3.791758e+00
21               Age_Newest_TL  3.603279e+00
34               num_sub_12mts  3.107404e+00
51                     CC_Flag  3.092952e+00
46            NETMONTHLYINCOME  2.888372e+00
11             Tot_Missed_Pmnt  2.846499e+00
52                     PL_Flag  2.786162e+00
38                     num_lss  2.729279e+00
33                num_sub_6mts  2.548197e+00
57                     HL_Flag  2.455140e+00
35                     num_dbt  2.195876e+00
32                     num_sub  1.567662e+00
22   time_since_recent_payment  1.333049e+00
50       pct_currentBal_all_TL  1.007305e+00
Dropping CC_enq with VIF: 117833938.23538524
                       Feature          VIF
42                     tot_enq  9687.459471
43       time_since_recent_enq  9604.941282
58                Credit_Score  3251.817109
47      pct_of_active_TLs_ever  1520.650492
6                pct_closed_tl  1023.638546
17                  Secured_TL    84.704872
14                     Gold_TL    55.220220
18                Unsecured_TL    48.417644
31               num_std_12mts    25.947911
44                         AGE    21.922039
7         Total_TL_opened_L12M    21.539150
13                 Consumer_TL    21.228139
52      pct_PL_enq_L6m_of_L12m    21.159500
54      pct_PL_enq_L6m_of_ever    20.259726
1                Tot_Active_TL    19.751981
30                num_std_6mts    16.720579
53      pct_CC_enq_L6m_of_L12m    16.305709
55      pct_CC_enq_L6m_of_ever    15.571551
27           num_times_30p_dpd    14.519350
19                    Other_TL    13.407484
8           Tot_TL_closed_L12M    11.097811
2          Total_TL_opened_L6M    10.579248
37               num_dbt_12mts     9.302410
28           num_times_60p_dpd     8.465900
48  pct_opened_TLs_L6m_of_L12m     8.299567
25             num_deliq_12mts     8.183436
23        num_times_delinquent     8.136804
3            Tot_TL_closed_L6M     7.980764
40               num_lss_12mts     7.950441
9             pct_tl_open_L12M     7.893116
4              pct_tl_open_L6M     7.785471
20               Age_Oldest_TL     7.397336
36                num_dbt_6mts     7.384496
29                     num_std     7.232884
26           num_deliq_6_12mts     6.928929
39                num_lss_6mts     6.355624
10          pct_tl_closed_L12M     6.120405
24   max_recent_level_of_deliq     5.405478
41       recent_level_of_deliq     4.967487
16                       PL_TL     4.938415
5            pct_tl_closed_L6M     4.781706
15                     Home_TL     4.621497
57                     GL_Flag     4.409784
0                   PROSPECTID     4.004266
46         Time_With_Curr_Empr     3.946391
12                       CC_TL     3.790236
21               Age_Newest_TL     3.589987
34               num_sub_12mts     3.107393
50                     CC_Flag     3.090297
45            NETMONTHLYINCOME     2.878511
11             Tot_Missed_Pmnt     2.836061
51                     PL_Flag     2.783928
38                     num_lss     2.729187
33                num_sub_6mts     2.548195
56                     HL_Flag     2.454938
35                     num_dbt     2.195607
32                     num_sub     1.567306
22   time_since_recent_payment     1.332969
49       pct_currentBal_all_TL     1.007300
Dropping tot_enq with VIF: 9687.459470600565
                       Feature          VIF
57                Credit_Score  2812.775887
46      pct_of_active_TLs_ever  1331.014195
6                pct_closed_tl   897.943675
17                  Secured_TL    84.581151
14                     Gold_TL    55.134936
18                Unsecured_TL    48.384769
31               num_std_12mts    25.879429
43                         AGE    21.909971
7         Total_TL_opened_L12M    21.538429
13                 Consumer_TL    21.193122
51      pct_PL_enq_L6m_of_L12m    21.155553
53      pct_PL_enq_L6m_of_ever    20.258626
1                Tot_Active_TL    19.742962
30                num_std_6mts    16.720076
52      pct_CC_enq_L6m_of_L12m    16.304127
54      pct_CC_enq_L6m_of_ever    15.569949
27           num_times_30p_dpd    14.519333
19                    Other_TL    13.387281
8           Tot_TL_closed_L12M    11.097811
2          Total_TL_opened_L6M    10.569697
37               num_dbt_12mts     9.302082
28           num_times_60p_dpd     8.465895
47  pct_opened_TLs_L6m_of_L12m     8.287192
25             num_deliq_12mts     8.172819
23        num_times_delinquent     8.124377
3            Tot_TL_closed_L6M     7.980532
40               num_lss_12mts     7.950388
9             pct_tl_open_L12M     7.829237
4              pct_tl_open_L6M     7.779077
36                num_dbt_6mts     7.384176
29                     num_std     7.230769
20               Age_Oldest_TL     7.129445
26           num_deliq_6_12mts     6.927915
39                num_lss_6mts     6.355435
10          pct_tl_closed_L12M     6.116645
24   max_recent_level_of_deliq     5.405454
41       recent_level_of_deliq     4.960179
16                       PL_TL     4.936094
5            pct_tl_closed_L6M     4.781702
15                     Home_TL     4.620407
56                     GL_Flag     4.409151
0                   PROSPECTID     4.004245
45         Time_With_Curr_Empr     3.945612
12                       CC_TL     3.790001
21               Age_Newest_TL     3.386446
34               num_sub_12mts     3.107325
49                     CC_Flag     3.090159
44            NETMONTHLYINCOME     2.878225
11             Tot_Missed_Pmnt     2.834544
50                     PL_Flag     2.783880
38                     num_lss     2.729019
33                num_sub_6mts     2.548175
55                     HL_Flag     2.454187
35                     num_dbt     2.194952
32                     num_sub     1.566872
42       time_since_recent_enq     1.336859
22   time_since_recent_payment     1.330922
48       pct_currentBal_all_TL     1.007239
Dropping Credit_Score with VIF: 2812.775887031287
                       Feature        VIF
17                  Secured_TL  84.579507
14                     Gold_TL  55.133634
18                Unsecured_TL  48.384769
31               num_std_12mts  25.578249
43                         AGE  21.899601
7         Total_TL_opened_L12M  21.535542
13                 Consumer_TL  21.192855
51      pct_PL_enq_L6m_of_L12m  20.932765
53      pct_PL_enq_L6m_of_ever  20.254610
1                Tot_Active_TL  19.738835
30                num_std_6mts  16.716047
52      pct_CC_enq_L6m_of_L12m  16.267075
46      pct_of_active_TLs_ever  15.925722
54      pct_CC_enq_L6m_of_ever  15.569666
27           num_times_30p_dpd  14.519293
6                pct_closed_tl  14.136069
19                    Other_TL  13.387258
8           Tot_TL_closed_L12M  11.096297
2          Total_TL_opened_L6M  10.565699
37               num_dbt_12mts   9.302068
28           num_times_60p_dpd   8.464520
47  pct_opened_TLs_L6m_of_L12m   8.287139
25             num_deliq_12mts   8.150554
23        num_times_delinquent   8.044413
3            Tot_TL_closed_L6M   7.980530
40               num_lss_12mts   7.950187
9             pct_tl_open_L12M   7.828582
4              pct_tl_open_L6M   7.777120
36                num_dbt_6mts   7.383703
29                     num_std   7.230723
26           num_deliq_6_12mts   6.904487
39                num_lss_6mts   6.355419
10          pct_tl_closed_L12M   6.116500
20               Age_Oldest_TL   5.458518
24   max_recent_level_of_deliq   5.401068
41       recent_level_of_deliq   4.936696
16                       PL_TL   4.934508
5            pct_tl_closed_L6M   4.781537
15                     Home_TL   4.620398
56                     GL_Flag   4.409151
0                   PROSPECTID   4.004122
45         Time_With_Curr_Empr   3.943144
12                       CC_TL   3.789850
21               Age_Newest_TL   3.305954
34               num_sub_12mts   3.107124
49                     CC_Flag   3.090023
44            NETMONTHLYINCOME   2.877029
11             Tot_Missed_Pmnt   2.833772
50                     PL_Flag   2.782990
38                     num_lss   2.729010
33                num_sub_6mts   2.548149
55                     HL_Flag   2.449798
35                     num_dbt   2.194633
32                     num_sub   1.566618
42       time_since_recent_enq   1.332960
22   time_since_recent_payment   1.330909
48       pct_currentBal_all_TL   1.007239
Dropping Secured_TL with VIF: 84.57950669764814
                       Feature        VIF
30               num_std_12mts  25.542276
42                         AGE  21.826340
7         Total_TL_opened_L12M  21.456647
50      pct_PL_enq_L6m_of_L12m  20.929217
52      pct_PL_enq_L6m_of_ever  20.246994
1                Tot_Active_TL  17.818372
17                Unsecured_TL  17.159301
29                num_std_6mts  16.707223
51      pct_CC_enq_L6m_of_L12m  16.265103
45      pct_of_active_TLs_ever  15.829565
53      pct_CC_enq_L6m_of_ever  15.568344
26           num_times_30p_dpd  14.518359
6                pct_closed_tl  13.616848
13                 Consumer_TL  11.131337
8           Tot_TL_closed_L12M  10.880059
2          Total_TL_opened_L6M  10.565181
36               num_dbt_12mts   9.302043
27           num_times_60p_dpd   8.442722
46  pct_opened_TLs_L6m_of_L12m   8.286924
24             num_deliq_12mts   8.147635
3            Tot_TL_closed_L6M   7.979652
22        num_times_delinquent   7.953849
39               num_lss_12mts   7.949964
9             pct_tl_open_L12M   7.828484
4              pct_tl_open_L6M   7.774295
35                num_dbt_6mts   7.383668
28                     num_std   7.229846
25           num_deliq_6_12mts   6.903764
38                num_lss_6mts   6.355312
10          pct_tl_closed_L12M   6.044366
23   max_recent_level_of_deliq   5.400216
19               Age_Oldest_TL   4.982859
40       recent_level_of_deliq   4.936440
5            pct_tl_closed_L6M   4.781419
15                     Home_TL   4.459142
55                     GL_Flag   4.404104
0                   PROSPECTID   4.004122
44         Time_With_Curr_Empr   3.939696
16                       PL_TL   3.582348
12                       CC_TL   3.379938
20               Age_Newest_TL   3.210432
33               num_sub_12mts   3.106526
48                     CC_Flag   3.089991
18                    Other_TL   2.991394
43            NETMONTHLYINCOME   2.876362
11             Tot_Missed_Pmnt   2.806405
49                     PL_Flag   2.775033
37                     num_lss   2.727365
32                num_sub_6mts   2.548133
54                     HL_Flag   2.364003
34                     num_dbt   2.194370
14                     Gold_TL   2.058563
31                     num_sub   1.566382
21   time_since_recent_payment   1.328842
41       time_since_recent_enq   1.320235
47       pct_currentBal_all_TL   1.007133
Dropping num_std_12mts with VIF: 25.542276396342377
                       Feature        VIF
41                         AGE  21.825490
7         Total_TL_opened_L12M  21.456544
49      pct_PL_enq_L6m_of_L12m  20.929155
51      pct_PL_enq_L6m_of_ever  20.246204
1                Tot_Active_TL  17.787744
17                Unsecured_TL  17.158965
50      pct_CC_enq_L6m_of_L12m  16.265098
44      pct_of_active_TLs_ever  15.826467
52      pct_CC_enq_L6m_of_ever  15.568165
26           num_times_30p_dpd  14.517708
6                pct_closed_tl  13.610497
13                 Consumer_TL  11.124967
8           Tot_TL_closed_L12M  10.792574
2          Total_TL_opened_L6M  10.520131
35               num_dbt_12mts   9.301742
27           num_times_60p_dpd   8.440991
45  pct_opened_TLs_L6m_of_L12m   8.280229
24             num_deliq_12mts   8.144563
3            Tot_TL_closed_L6M   7.967998
22        num_times_delinquent   7.952141
38               num_lss_12mts   7.949300
9             pct_tl_open_L12M   7.822203
4              pct_tl_open_L6M   7.771935
34                num_dbt_6mts   7.383649
25           num_deliq_6_12mts   6.884440
37                num_lss_6mts   6.355178
10          pct_tl_closed_L12M   6.038599
23   max_recent_level_of_deliq   5.400106
19               Age_Oldest_TL   4.981350
39       recent_level_of_deliq   4.936440
28                     num_std   4.848658
5            pct_tl_closed_L6M   4.781147
15                     Home_TL   4.458329
54                     GL_Flag   4.403276
0                   PROSPECTID   4.004085
43         Time_With_Curr_Empr   3.939568