In [44]:
import pandas as pd

In [45]:
pd.set_option('display.max_columns',None)

In [46]:
df1 = pd.read_excel("case_study1.xlsx")
df2 = pd.read_excel("case_study2.xlsx")

In [47]:
df1.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,Tot_TL_closed_L12M,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,Auto_TL,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,0,0,0.00,0.0,0,0,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,1,0,1.00,0.0,0,0,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,2,0,0.25,0.0,1,1,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,1,0,1.00,0.0,1,0,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,0,0,0.00,0.0,0,1,0,0,0,0,0,3,0,2,131,32

In [48]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,max_deliq_6mts,max_deliq_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,num_std_6mts,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_6mts,num_dbt_12mts,num_lss,num_lss_6mts,num_lss_12mts,recent_level_of_deliq,tot_enq,CC_enq,CC_enq_L6m,CC_enq_L12m,PL_enq,PL_enq_L6m,PL_enq_L12m,time_since_recent_enq,enq_L12m,enq_L6m,enq_L3m,MARITALSTATUS,EDUCATION,AGE,GENDER,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_of_active_TLs_ever,pct_opened_TLs_L6m_of_L12m,pct_currentBal_all_TL,CC_utilization,CC_Flag,PL_utilization,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,-99999,-99999,0,0,21,5,11,0,0,0,0,0,0,0,0,0,29,6,0,0,0,6,0,0,566,0,0,0,Married,12TH,48,M,51000,114,0.200,0.0,0.798,-99999.0,0,0.798,1,0.0,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,209,1,0,0,Single,GRADUATE,23,F,19000,50,1.000,0.0,0.370,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,25,25,0,0,10,5,10,0,0,0,0,0,0,0,0,0,25,4,0,0,0,0,0,0,587,0,0,0,Married,SSC,40,M,18,191,1.000,0.5,0.585,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,-99999,-99999,0,0,5,4,5,0,0,0,0,0,0,0,0,0,0,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,Married,SSC,34,M,10000,246,1.000,1.0,0.990,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,-99999,-99999,0,0,53,4,16,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3951,0,0,0,Married,POST-GRADUATE,48,M,15000,75,0.333,0.0,0.000,-99999.0,0,-99999.000,0,0.0,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

In [49]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PROSPECTID            51336 non-null  int64
 1   Total_TL              51336 non-null  int64
 2   Tot_Closed_TL         51336 non-null  int64
 3   Tot_Active_TL         51336 non-null  int64
 4   Total_TL_opened_L6M   51336 non-null  int64
 5   Tot_TL_closed_L6M     51336 non-null  int64
 6   pct_tl_open_L6M       51336 non-null  float64
 7   pct_tl_closed_L6M     51336 non-null  float64
 8   pct_active_tl         51336 non-null  float64
 9   pct_closed_tl         51336 non-null  float64
 10  Total_TL_opened_L12M  51336 non-null  int64
 11  Tot_TL_closed_L12M    51336 non-null  int64
 12  pct_tl_open_L12M      51336 non-null  float64
 13  pct_tl_closed_L12M    51336 non-null  float64
 14  Tot_Missed_Pmnt       51336 non-null  int64
 15  Auto_TL               51336 non-null  int64
 16  CC_TL                 51336 non-null  int64
 17  Consumer_TL           51336 non-null  int64
 18  Gold_TL               51336 non-null  int64
 19  Home_TL               51336 non-null  int64
 20  PL_TL                 51336 non-null  int64
 21  Secured_TL            51336 non-null  int64
 22  Unsecured_TL          51336 non-null  int64
 23  Other_TL              51336 non-null  int64
 24  Age_Oldest_TL         51336 non-null  int64
 25  Age_Newest_TL         51336 non-null  int64
dtypes: float64(6), int64(20)
memory usage: 10.2 MB

In [50]:
print(df1.shape)
print(df2.shape)

(51336, 26)
(51336, 62)

## Data Cleaning

In [51]:
df1 = df1[df1['Age_Oldest_TL'] != -99999]

In [52]:
df1.shape

(51296, 26)

In [53]:
columns_to_removed = []

In [54]:
for i in df2.columns:
    count = (df2[i] == -99999).sum()
    percentage =round((count/len(df2))*100)
    if count>0:
        print(f'columns {i},count {count},percentage {percentage}')

columns time_since_recent_payment,count 4291,percentage 8
columns time_since_first_deliquency,count 35949,percentage 70
columns time_since_recent_deliquency,count 35949,percentage 70
columns max_delinquency_level,count 35949,percentage 70
columns max_deliq_6mts,count 12890,percentage 25
columns max_deliq_12mts,count 10832,percentage 21
columns tot_enq,count 6321,percentage 12
columns CC_enq,count 6321,percentage 12
columns CC_enq_L6m,count 6321,percentage 12
columns CC_enq_L12m,count 6321,percentage 12
columns PL_enq,count 6321,percentage 12
columns PL_enq_L6m,count 6321,percentage 12
columns PL_enq_L12m,count 6321,percentage 12
columns time_since_recent_enq,count 6321,percentage 12
columns enq_L12m,count 6321,percentage 12
columns enq_L6m,count 6321,percentage 12
columns enq_L3m,count 6321,percentage 12
columns pct_currentBal_all_TL,count 72,percentage 0
columns CC_utilization,count 47636,percentage 93
columns PL_utilization,count 44435,percentage 87
columns max_unsec_exposure_inPct,count 23178,percentage 45

In [55]:
for i in df2.columns:
    if (df2[i] == -99999).sum() > 10000:
        columns_to_removed.append(i)
        print(i)

time_since_first_deliquency
time_since_recent_deliquency
max_delinquency_level
max_deliq_6mts
max_deliq_12mts
CC_utilization
PL_utilization
max_unsec_exposure_inPct

In [56]:
columns_to_removed

['time_since_first_deliquency',
 'time_since_recent_deliquency',
 'max_delinquency_level',
 'max_deliq_6mts',
 'max_deliq_12mts',
 'CC_utilization',
 'PL_utilization',
 'max_unsec_exposure_inPct']

In [57]:
df2 = df2.drop(columns=columns_to_removed)

In [58]:
df2.shape

(51336, 54)

In [59]:
common_columns = []

for col in df1.columns:
    if col in df2.columns:
        common_columns.append(col)

print(common_columns)

['PROSPECTID']

In [60]:
df = pd.merge(df1,df2,on='PROSPECTID',how='inner')
df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,Tot_TL_closed_L12M,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,Auto_TL,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,num_std_6mts,num_std_12mts,num_sub,num_sub_6mts,num_sub_12mts,num_dbt,num_dbt_6mts,num_dbt_12mts,num_lss,num_lss_6mts,num_lss_12mts,recent_level_of_deliq,tot_enq,CC_enq,CC_enq_L6m,CC_enq_L12m,PL_enq,PL_enq_L6m,PL_enq_L12m,time_since_recent_enq,enq_L12m,enq_L6m,enq_L3m,MARITALSTATUS,EDUCATION,AGE,GENDER,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_of_active_TLs_ever,pct_opened_TLs_L6m_of_L12m,pct_currentBal_all_TL,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,0,0,0.00,0.0,0,0,0,0,1,0,4,1,4,0,72,18,549,11,29,0,0,0,0,0,21,5,11,0,0,0,0,0,0,0,0,0,29,6,0,0,0,6,0,0,566,0,0,0,Married,12TH,48,M,51000,114,0.200,0.0,0.798,0,1,0.0,0.0,0.0,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,1,0,1.00,0.0,0,0,0,1,0,0,0,0,1,0,7,7,47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,209,1,0,0,Single,GRADUATE,23,F,19000,50,1.000,0.0,0.370,0,0,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,2,0,0.25,0.0,1,1,0,6,1,0,0,2,6,0,47,2,302,9,25,1,9,8,0,0,10,5,10,0,0,0,0,0,0,0,0,0,25,4,0,0,0,0,0,0,587,0,0,0,Married,SSC,40,M,18,191,1.000,0.5,0.585,0,0,0.0,0.0,0.0,0.0,1,0,ConsumerLoan,others,693,P2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,1,0,1.00,0.0,1,0,0,0,0,0,0,0,1,1,5,5,-99999,0,0,0,0,0,0,0,5,4,5,0,0,0,0,0,0,0,0,0,0,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,Married,SSC,34,M,10000,246,1.000,1.0,0.990,0,0,0.0,0.0,0.0,0.0,0,0,others,others,673,P2
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,0,0,0.00,0.0,0,1,0,0,0,0,0,3,0,2,131,32,583,0,0,0,0,0,0,0,53,4,16,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3951,0,0,0,Married,POST-GRADUATE,48,M,15000,75,0.333,0.0,0.000,0,0,0.0,0.0,0.0,0.0,0,0,AL,AL,753,P1

In [61]:
df.shape

(51296, 79)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51296 entries, 0 to 51295
Data columns (total 79 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROSPECTID                  51296 non-null  int64
 1   Total_TL                    51296 non-null  int64
 2   Tot_Closed_TL               51296 non-null  int64
 3   Tot_Active_TL               51296 non-null  int64
 4   Total_TL_opened_L6M         51296 non-null  int64
 5   Tot_TL_closed_L6M           51296 non-null  int64
 6   pct_tl_open_L6M             51296 non-null  float64
 7   pct_tl_closed_L6M           51296 non-null  float64
 8   pct_active_tl               51296 non-null  float64
 9   pct_closed_tl               51296 non-null  float64
 10  Total_TL_opened_L12M        51296 non-null  int64
 11  Tot_TL_closed_L12M          51296 non-null  int64
 12  pct_tl_open_L12M            51296 non-null  float64
 13  pct_tl_closed_L12M          51296 non-null  float64
 14  Tot_Missed_Pmnt             51296 non-null  int64
 15  Auto_TL                     51296 non-null  int64
 16  CC_TL                       51296 non-null  int64
 17  Consumer_TL                 51296 non-null  int64
 18  Gold_TL                     51296 non-null  int64
 19  Home_TL                     51296 non-null  int64
 20  PL_TL                       51296 non-null  int64
 21  Secured_TL                  51296 non-null  int64
 22  Unsecured_TL                51296 non-null  int64
 23  Other_TL                    51296 non-null  int64
 24  Age_Oldest_TL               51296 non-null  int64
 25  Age_Newest_TL               51296 non-null  int64
 26  time_since_recent_payment   51296 non-null  int64
 27  num_times_delinquent        51296 non-null  int64
 28  max_recent_level_of_deliq   51296 non-null  int64
 29  num_deliq_6mts              51296 non-null  int64
 30  num_deliq_12mts             51296 non-null  int64
 31  num_deliq_6_12mts           51296 non-null  int64
 32  num_times_30p_dpd           51296 non-null  int64
 33  num_times_60p_dpd           51296 non-null  int64
 34  num_std                     51296 non-null  int64
 35  num_std_6mts                51296 non-null  int64
 36  num_std_12mts               51296 non-null  int64
 37  num_sub                     51296 non-null  int64
 38  num_sub_6mts                51296 non-null  int64
 39  num_sub_12mts               51296 non-null  int64
 40  num_dbt                     51296 non-null  int64
 41  num_dbt_6mts                51296 non-null  int64
 42  num_dbt_12mts               51296 non-null  int64
 43  num_lss                     51296 non-null  int64
 44  num_lss_6mts                51296 non-null  int64
 45  num_lss_12mts               51296 non-null  int64
 46  recent_level_of_deliq       51296 non-null  int64
 47  tot_enq                     51296 non-null  int64
 48  CC_enq                      51296 non-null  int64
 49  CC_enq_L6m                  51296 non-null  int64
 50  CC_enq_L12m                 51296 non-null  int64
 51  PL_enq                      51296 non-null  int64
 52  PL_enq_L6m                  51296 non-null  int64
 53  PL_enq_L12m                 51296 non-null  int64
 54  time_since_recent_enq       51296 non-null  int64
 55  enq_L12m                    51296 non-null  int64
 56  enq_L6m                     51296 non-null  int64
 57  enq_L3m                     51296 non-null  int64
 58  MARITALSTATUS               51296 non-null  object
 59  EDUCATION                   51296 non-null  object
 60  AGE                         51296 non-null  int64
 61  GENDER                      51296 non-null  object
 62  NETMONTHLYINCOME            51296 non-null  int64
 63  Time_With_Curr_Empr         51296 non-null  int64
 64  pct_of_active_TLs_ever      51296 non-null  float64
 65  pct_opened_TLs_L6m_of_L12m  51296 non-null  float64
 66  pct_currentBal_all_TL       51296 non-null  float64
 67  CC_Flag                     51296 non-null  int64
 68  PL_Flag                     51296 non-null  int64
 69  pct_PL_enq_L6m_of_L12m      51296 non-null  float64
 70  pct_CC_enq_L6m_of_L12m      51296 non-null  float64
 71  pct_PL_enq_L6m_of_ever      51296 non-null  float64
 72  pct_CC_enq_L6m_of_ever      51296 non-null  float64
 73  HL_Flag                     51296 non-null  int64
 74  GL_Flag                     51296 non-null  int64
 75  last_prod_enq2              51296 non-null  object
 76  first_prod_enq2             51296 non-null  object
 77  Credit_Score                51296 non-null  int64
 78  Approved_Flag               51296 non-null  object
dtypes: float64(13), int64(60), object(6)
memory usage: 30.9+ MB

In [63]:
# To find categorical columns 
for i in df.columns:
    if df[i].dtypes == 'object':
        print(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [64]:
#Check weather categorical columns are having some impacvt or not - Hypothesis Testing

## Feature Selection

In [65]:
df.MARITALSTATUS.value_counts()

MARITALSTATUS
Married    37724
Single     13572
Name: count, dtype: int64

In [66]:
df.EDUCATION.value_counts()

EDUCATION
GRADUATE          16655
12TH              14458
SSC                9268
UNDER GRADUATE     5491
OTHERS             2915
POST-GRADUATE      2240
PROFESSIONAL        269
Name: count, dtype: int64

In [67]:
df.GENDER.value_counts()

GENDER
M    45211
F     6085
Name: count, dtype: int64

In [68]:
df.MARITALSTATUS.value_counts()

MARITALSTATUS
Married    37724
Single     13572
Name: count, dtype: int64

In [69]:
df.Approved_Flag.value_counts()

Approved_Flag
P2    32162
P3     7449
P4     5882
P1     5803
Name: count, dtype: int64

In [70]:
df.first_prod_enq2.value_counts()

first_prod_enq2
others          28095
ConsumerLoan    11852
PL               4885
AL               2869
CC               2187
HL               1408
Name: count, dtype: int64

In [71]:
df.last_prod_enq2.value_counts()

last_prod_enq2
others          20808
ConsumerLoan    17782
PL               7955
CC               2338
AL               1511
HL                902
Name: count, dtype: int64

## Hypothesis Testing

**Chi-Squared Test**
To check whether the categorical features are associated with output feature or not. It means whether we can keep categorical feature or we should remove it

### Hypothesis Testing for Feature Selection

For each categorical feature, we define the hypotheses as follows:

#### Null Hypothesis (H0):
There is **no relationship** between the feature and the target variable (they are independent).  
- The feature **does not influence** the target.
- It **should be removed** if (H0) is true.
- 
#### Alternative Hypothesis (H1):
There **is a relationship** between the feature and the target variable (they are dependent).  
- The feature **affects** the target.
- It **should be kept** if (H0) is rejected.

In [72]:
import pandas as pd
from scipy.stats import chi2_contingency

for i in ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
    chi2, pval, dof, expected = chi2_contingency(pd.crosstab(df[i], df['Approved_Flag']))
    print(i, '---', pval)

MARITALSTATUS --- 2.7347247145640217e-257
EDUCATION --- 6.772122013692765e-38
GENDER --- 0.00025924146444508505
last_prod_enq2 --- 0.0
first_prod_enq2 --- 0.0

In [73]:
import numpy as np
from statsmodels.stats.outliers_influence import variance_inflation_factor

#Check VIF to check Multi Colinearity

# Selecting numerical features
numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()
vif_data = df[numeric_columns].copy()

# Set VIF threshold
vif_threshold = 6
columns_to_be_kept = []

while True:
    vif_values = [variance_inflation_factor(vif_data.values, i) for i in range(vif_data.shape[1])]
    vif_df = pd.DataFrame({"Feature": vif_data.columns, "VIF": vif_values})
    
    # Print VIF values
    print(vif_df.sort_values(by="VIF", ascending=False))
    
    max_vif = vif_df["VIF"].max()
    
    if max_vif < vif_threshold:
        break  # Stop if all VIFs are below threshold
    
    # Drop feature with highest VIF
    drop_feature = vif_df.loc[vif_df["VIF"] == max_vif, "Feature"].values[0]
    print(f"Dropping {drop_feature} with VIF: {max_vif}")
    vif_data.drop(columns=[drop_feature], inplace=True)

# Store final features with low VIF
columns_to_be_kept = vif_data.columns.tolist()

print("\nFinal Features with Low VIF:\n", columns_to_be_kept)

                      Feature       VIF
1                    Total_TL       inf
3               Tot_Active_TL       inf
2               Tot_Closed_TL       inf
8               pct_active_tl       inf
20                      PL_TL       inf
..                        ...       ...
60        Time_With_Curr_Empr  1.265841
26  time_since_recent_payment  1.230058
59           NETMONTHLYINCOME  1.055621
63      pct_currentBal_all_TL  1.005981
0                  PROSPECTID  1.001322

[73 rows x 2 columns]
Dropping Total_TL with VIF: inf
                      Feature       VIF
1               Tot_Closed_TL       inf
2               Tot_Active_TL       inf
7               pct_active_tl       inf
19                      PL_TL       inf
20                 Secured_TL       inf
..                        ...       ...
59        Time_With_Curr_Empr  1.265841
25  time_since_recent_payment  1.230058
58           NETMONTHLYINCOME  1.055621
62      pct_currentBal_all_TL  1.005981
0                  PROSPECTID  1.001322

[72 rows x 2 columns]
Dropping Tot_Closed_TL with VIF: inf
                      Feature       VIF
6               pct_active_tl       inf
17                    Home_TL       inf
18                      PL_TL       inf
19                 Secured_TL       inf
20               Unsecured_TL       inf
..                        ...       ...
58        Time_With_Curr_Empr  1.265841
24  time_since_recent_payment  1.230058
57           NETMONTHLYINCOME  1.055621
61      pct_currentBal_all_TL  1.005981
0                  PROSPECTID  1.001322

[71 rows x 2 columns]
Dropping pct_active_tl with VIF: inf
                      Feature       VIF
16                    Home_TL       inf
17                      PL_TL       inf
18                 Secured_TL       inf
19               Unsecured_TL       inf
13                      CC_TL       inf
..                        ...       ...
57        Time_With_Curr_Empr  1.265841
23  time_since_recent_payment  1.230058
56           NETMONTHLYINCOME  1.055621
60      pct_currentBal_all_TL  1.005981
0                  PROSPECTID  1.001322

[70 rows x 2 columns]
Dropping Auto_TL with VIF: inf
                      Feature           VIF
27          num_deliq_6_12mts           inf
25             num_deliq_6mts           inf
26            num_deliq_12mts           inf
46                CC_enq_L12m  1.311116e+10
45                 CC_enq_L6m  1.126722e+10
..                        ...           ...
56        Time_With_Curr_Empr  1.265841e+00
22  time_since_recent_payment  1.230058e+00
55           NETMONTHLYINCOME  1.055621e+00
59      pct_currentBal_all_TL  1.005981e+00
0                  PROSPECTID  1.001322e+00

[69 rows x 2 columns]
Dropping num_deliq_6mts with VIF: inf
                      Feature           VIF
45                CC_enq_L12m  1.311116e+10
44                 CC_enq_L6m  1.126722e+10
47                 PL_enq_L6m  7.095182e+09
48                PL_enq_L12m  6.397795e+09
43                     CC_enq  3.176226e+09
..                        ...           ...
55        Time_With_Curr_Empr  1.265841e+00
22  time_since_recent_payment  1.230058e+00
54           NETMONTHLYINCOME  1.055621e+00
58      pct_currentBal_all_TL  1.005981e+00
0                  PROSPECTID  1.001322e+00

[68 rows x 2 columns]
Dropping CC_enq_L12m with VIF: 13111164046.395334
                      Feature           VIF
46                 PL_enq_L6m  7.091635e+09
47                PL_enq_L12m  6.351180e+09
44                 CC_enq_L6m  4.179793e+09
50                    enq_L6m  2.423038e+09
45                     PL_enq  2.073845e+09
..                        ...           ...
54        Time_With_Curr_Empr  1.265819e+00
22  time_since_recent_payment  1.230001e+00
53           NETMONTHLYINCOME  1.055575e+00
57      pct_currentBal_all_TL  1.005978e+00
0                  PROSPECTID  1.001222e+00

[67 rows x 2 columns]
Dropping PL_enq_L6m with VIF: 7091635137.846458
                      Feature           VIF
44                 CC_enq_L6m  3.625474e+09
46                PL_enq_L12m  3.317603e+09
45                     PL_enq  2.073405e+09
43                     CC_enq  1.927405e+09
49                    enq_L6m  1.927196e+09
..                        ...           ...
53        Time_With_Curr_Empr  1.265779e+00
22  time_since_recent_payment  1.229994e+00
52           NETMONTHLYINCOME  1.055567e+00
56      pct_currentBal_all_TL  1.005977e+00
0                  PROSPECTID  1.001221e+00

[66 rows x 2 columns]
Dropping CC_enq_L6m with VIF: 3625473653.7062945
                      Feature           VIF
45                PL_enq_L12m  3.087314e+09
44                     PL_enq  2.073405e+09
48                    enq_L6m  1.896049e+09
49                    enq_L3m  1.414356e+09
47                   enq_L12m  1.156901e+09
..                        ...           ...
52        Time_With_Curr_Empr  1.265389e+00
22  time_since_recent_payment  1.229710e+00
51           NETMONTHLYINCOME  1.055457e+00
55      pct_currentBal_all_TL  1.005969e+00
0                  PROSPECTID  1.001221e+00

[65 rows x 2 columns]
Dropping PL_enq_L12m with VIF: 3087314272.434116
                      Feature           VIF
47                    enq_L6m  1.893349e+09
48                    enq_L3m  1.406038e+09
46                   enq_L12m  1.014820e+09
43                     CC_enq  6.524960e+08
44                     PL_enq  5.620835e+08
..                        ...           ...
51        Time_With_Curr_Empr  1.265272e+00
22  time_since_recent_payment  1.229694e+00
50           NETMONTHLYINCOME  1.055407e+00
54      pct_currentBal_all_TL  1.005966e+00
0                  PROSPECTID  1.001221e+00

[64 rows x 2 columns]
Dropping enq_L6m with VIF: 1893349471.6923487
                      Feature           VIF
47                    enq_L3m  7.826205e+08
43                     CC_enq  6.484642e+08
46                   enq_L12m  5.876474e+08
44                     PL_enq  5.614738e+08
42                    tot_enq  2.600131e+08
..                        ...           ...
50        Time_With_Curr_Empr  1.265266e+00
22  time_since_recent_payment  1.229644e+00
49           NETMONTHLYINCOME  1.055372e+00
53      pct_currentBal_all_TL  1.005963e+00
0                  PROSPECTID  1.001135e+00

[63 rows x 2 columns]
Dropping enq_L3m with VIF: 782620530.8217674
                      Feature           VIF
44                     PL_enq  5.177602e+08
46                   enq_L12m  4.565308e+08
43                     CC_enq  4.346009e+08
42                    tot_enq  2.377953e+08
45      time_since_recent_enq  8.489851e+03
..                        ...           ...
49        Time_With_Curr_Empr  1.265265e+00
22  time_since_recent_payment  1.228692e+00
48           NETMONTHLYINCOME  1.055161e+00
52      pct_currentBal_all_TL  1.005956e+00
0                  PROSPECTID  1.001072e+00

[62 rows x 2 columns]
Dropping PL_enq with VIF: 517760228.9580271
                      Feature           VIF
45                   enq_L12m  4.244392e+08
42                    tot_enq  2.360736e+08
43                     CC_enq  1.858020e+08
44      time_since_recent_enq  8.474490e+03
49     pct_of_active_TLs_ever  1.914560e+03
..                        ...           ...
48        Time_With_Curr_Empr  1.265235e+00
22  time_since_recent_payment  1.228666e+00
47           NETMONTHLYINCOME  1.054479e+00
51      pct_currentBal_all_TL  1.005948e+00
0                  PROSPECTID  1.001059e+00

[61 rows x 2 columns]
Dropping enq_L12m with VIF: 424439185.7762248
                       Feature           VIF
43                      CC_enq  1.033492e+08
42                     tot_enq  1.033130e+08
44       time_since_recent_enq  8.474121e+03
48      pct_of_active_TLs_ever  1.779460e+03
6                pct_closed_tl  1.201185e+03
17                  Secured_TL  7.362919e+01
14                     Gold_TL  5.374294e+01
18                Unsecured_TL  3.528396e+01
31               num_std_12mts  2.177534e+01
53      pct_PL_enq_L6m_of_L12m  1.703723e+01
13                 Consumer_TL  1.686846e+01
55      pct_PL_enq_L6m_of_ever  1.651096e+01
54      pct_CC_enq_L6m_of_L12m  1.525728e+01
56      pct_CC_enq_L6m_of_ever  1.460509e+01
7         Total_TL_opened_L12M  1.432227e+01
30                num_std_6mts  1.399662e+01
27           num_times_30p_dpd  1.357337e+01
19                    Other_TL  1.152889e+01
1                Tot_Active_TL  1.085227e+01
37               num_dbt_12mts  9.297537e+00
8           Tot_TL_closed_L12M  8.829996e+00
28           num_times_60p_dpd  8.130091e+00
2          Total_TL_opened_L6M  7.998402e+00
40               num_lss_12mts  7.948840e+00
25             num_deliq_12mts  7.444472e+00
36                num_dbt_6mts  7.382371e+00
23        num_times_delinquent  7.119514e+00
3            Tot_TL_closed_L6M  6.718429e+00
26           num_deliq_6_12mts  6.400688e+00
39                num_lss_6mts  6.354572e+00
29                     num_std  6.107815e+00
4              pct_tl_open_L6M  5.623814e+00
49  pct_opened_TLs_L6m_of_L12m  5.338374e+00
24   max_recent_level_of_deliq  5.078869e+00
41       recent_level_of_deliq  4.692358e+00
10          pct_tl_closed_L12M  4.566583e+00
16                       PL_TL  4.455734e+00
15                     Home_TL  4.434722e+00
58                     GL_Flag  4.176531e+00
5            pct_tl_closed_L6M  4.025354e+00
9             pct_tl_open_L12M  3.917180e+00
12                       CC_TL  3.572908e+00
20               Age_Oldest_TL  3.520120e+00
59                Credit_Score  3.444027e+00
34               num_sub_12mts  3.102483e+00
51                     CC_Flag  2.816011e+00
38                     num_lss  2.727062e+00
33                num_sub_6mts  2.546387e+00
21               Age_Newest_TL  2.378882e+00
52                     PL_Flag  2.318126e+00
11             Tot_Missed_Pmnt  2.270782e+00
35                     num_dbt  2.192220e+00
57                     HL_Flag  1.789042e+00
32                     num_sub  1.558129e+00
45                         AGE  1.400350e+00
47         Time_With_Curr_Empr  1.265232e+00
22   time_since_recent_payment  1.228543e+00
46            NETMONTHLYINCOME  1.054054e+00
50       pct_currentBal_all_TL  1.005948e+00
0                   PROSPECTID  1.001037e+00
Dropping CC_enq with VIF: 103349158.71940835
                       Feature          VIF
42                     tot_enq  8497.444853
43       time_since_recent_enq  8467.815896
47      pct_of_active_TLs_ever  1520.650492
6                pct_closed_tl  1023.638546
17                  Secured_TL    69.913606
14                     Gold_TL    50.919540
18                Unsecured_TL    34.669006
31               num_std_12mts    21.711638
13                 Consumer_TL    16.844098
52      pct_PL_enq_L6m_of_L12m    16.843487
54      pct_PL_enq_L6m_of_ever    16.377250
53      pct_CC_enq_L6m_of_L12m    15.146991
55      pct_CC_enq_L6m_of_ever    14.558814
7         Total_TL_opened_L12M    14.321416
30                num_std_6mts    13.995270
27           num_times_30p_dpd    13.573353
19                    Other_TL    11.144351
1                Tot_Active_TL    10.785802
37               num_dbt_12mts     9.297506
8           Tot_TL_closed_L12M     8.828559
28           num_times_60p_dpd     8.129985
2          Total_TL_opened_L6M     7.995471
40               num_lss_12mts     7.948568
25             num_deliq_12mts     7.442581
36                num_dbt_6mts     7.382317
23        num_times_delinquent     7.119432
3            Tot_TL_closed_L6M     6.718408
26           num_deliq_6_12mts     6.400580
39                num_lss_6mts     6.354564
29                     num_std     6.094600
4              pct_tl_open_L6M     5.618994
48  pct_opened_TLs_L6m_of_L12m     5.329267
24   max_recent_level_of_deliq     5.078778
41       recent_level_of_deliq     4.687312
10          pct_tl_closed_L12M     4.566581
16                       PL_TL     4.455217
15                     Home_TL     4.433655
57                     GL_Flag     4.176469
5            pct_tl_closed_L6M     4.025351
9             pct_tl_open_L12M     3.910789
12                       CC_TL     3.571474
20               Age_Oldest_TL     3.390094
34               num_sub_12mts     3.102472
58                Credit_Score     2.956347
50                     CC_Flag     2.813594
38                     num_lss     2.726971
33                num_sub_6mts     2.546386
21               Age_Newest_TL     2.370107
51                     PL_Flag     2.316268
11             Tot_Missed_Pmnt     2.262456
35                     num_dbt     2.191952
56                     HL_Flag     1.788894
32                     num_sub     1.557775
44                         AGE     1.399678
46         Time_With_Curr_Empr     1.264920
22   time_since_recent_payment     1.228469
45            NETMONTHLYINCOME     1.050456
49       pct_currentBal_all_TL     1.005943
0                   PROSPECTID     1.001037
Dropping tot_enq with VIF: 8497.444853241377
                       Feature          VIF
46      pct_of_active_TLs_ever  1331.014195
6                pct_closed_tl   897.943675
17                  Secured_TL    69.811489
14                     Gold_TL    50.840898
18                Unsecured_TL    34.645466
31               num_std_12mts    21.654337
51      pct_PL_enq_L6m_of_L12m    16.840345
13                 Consumer_TL    16.816313
53      pct_PL_enq_L6m_of_ever    16.376361
52      pct_CC_enq_L6m_of_L12m    15.145522
54      pct_CC_enq_L6m_of_ever    14.557316
7         Total_TL_opened_L12M    14.320936
30                num_std_6mts    13.994849
27           num_times_30p_dpd    13.573337
19                    Other_TL    11.127558
1                Tot_Active_TL    10.780878
37               num_dbt_12mts     9.297179
8           Tot_TL_closed_L12M     8.828559
28           num_times_60p_dpd     8.129981
2          Total_TL_opened_L6M     7.988252
40               num_lss_12mts     7.948515
25             num_deliq_12mts     7.432925
36                num_dbt_6mts     7.381998
23        num_times_delinquent     7.108560
3            Tot_TL_closed_L6M     6.718213
26           num_deliq_6_12mts     6.399643
39                num_lss_6mts     6.354374
29                     num_std     6.092817
4              pct_tl_open_L6M     5.614379
47  pct_opened_TLs_L6m_of_L12m     5.321321
24   max_recent_level_of_deliq     5.078755
41       recent_level_of_deliq     4.680416
10          pct_tl_closed_L12M     4.563776
16                       PL_TL     4.453123
15                     Home_TL     4.432609
56                     GL_Flag     4.175869
5            pct_tl_closed_L6M     4.025347
9             pct_tl_open_L12M     3.879139
12                       CC_TL     3.571253
20               Age_Oldest_TL     3.267323
34               num_sub_12mts     3.102404
49                     CC_Flag     2.813469
38                     num_lss     2.726803
57                Credit_Score     2.557199
33                num_sub_6mts     2.546365
50                     PL_Flag     2.316228
11             Tot_Missed_Pmnt     2.261245
21               Age_Newest_TL     2.235730
35                     num_dbt     2.191297
55                     HL_Flag     1.788347
32                     num_sub     1.557344
43                         AGE     1.398907
45         Time_With_Curr_Empr     1.264670
22   time_since_recent_payment     1.226583
42       time_since_recent_enq     1.178588
44            NETMONTHLYINCOME     1.050351
48       pct_currentBal_all_TL     1.005881
0                   PROSPECTID     1.001032
Dropping pct_of_active_TLs_ever with VIF: 1331.0141946667754
                       Feature        VIF
17                  Secured_TL  84.579717
14                     Gold_TL  55.133578
18                Unsecured_TL  48.383539
56                Credit_Score  33.655153
31               num_std_12mts  25.591936
43                         AGE  21.862100
7         Total_TL_opened_L12M  21.537355
13                 Consumer_TL  21.192661
50      pct_PL_enq_L6m_of_L12m  20.944563
52      pct_PL_enq_L6m_of_ever  20.251193
1                Tot_Active_TL  19.702518
30                num_std_6mts  16.715854
51      pct_CC_enq_L6m_of_L12m  16.266298
53      pct_CC_enq_L6m_of_ever  15.569643
27           num_times_30p_dpd  14.519277
19                    Other_TL  13.384899
8           Tot_TL_closed_L12M  11.097320
2          Total_TL_opened_L6M  10.566464
37               num_dbt_12mts   9.302063
28           num_times_60p_dpd   8.464304
6                pct_closed_tl   8.440727
46  pct_opened_TLs_L6m_of_L12m   8.286881
25             num_deliq_12mts   8.151912
23        num_times_delinquent   8.046241
3            Tot_TL_closed_L6M   7.980438
40               num_lss_12mts   7.950163
9             pct_tl_open_L12M   7.818816
4              pct_tl_open_L6M   7.777770
36                num_dbt_6mts   7.383654
29                     num_std   7.230402
26           num_deliq_6_12mts   6.904087
39                num_lss_6mts   6.355426
10          pct_tl_closed_L12M   6.116642
20               Age_Oldest_TL   5.418676
24   max_recent_level_of_deliq   5.401709
16                       PL_TL   4.935497
41       recent_level_of_deliq   4.935056
5            pct_tl_closed_L6M   4.780960
15                     Home_TL   4.620107
55                     GL_Flag   4.409143
0                   PROSPECTID   3.998340
45         Time_With_Curr_Empr   3.942286
12                       CC_TL   3.789090
21               Age_Newest_TL   3.273187
34               num_sub_12mts   3.107074
48                     CC_Flag   3.090151
44            NETMONTHLYINCOME   2.873839
11             Tot_Missed_Pmnt   2.834337
49                     PL_Flag   2.782914
38                     num_lss   2.729017
33                num_sub_6mts   2.548142
54                     HL_Flag   2.448693
35                     num_dbt   2.194603
32                     num_sub   1.566632
42       time_since_recent_enq   1.334183
22   time_since_recent_payment   1.330792
47       pct_currentBal_all_TL   1.007238
Dropping Secured_TL with VIF: 84.5797168543514
                       Feature        VIF
55                Credit_Score  33.451866
30               num_std_12mts  25.554188
42                         AGE  21.789084
7         Total_TL_opened_L12M  21.458518
49      pct_PL_enq_L6m_of_L12m  20.940526
51      pct_PL_enq_L6m_of_ever  20.243687
1                Tot_Active_TL  17.778979
17                Unsecured_TL  17.159777
29                num_std_6mts  16.707133
50      pct_CC_enq_L6m_of_L12m  16.264178
52      pct_CC_enq_L6m_of_ever  15.568332
26           num_times_30p_dpd  14.518347
13                 Consumer_TL  11.131272
8           Tot_TL_closed_L12M  10.881328
2          Total_TL_opened_L6M  10.565968
36               num_dbt_12mts   9.302039
27           num_times_60p_dpd   8.442409
45  pct_opened_TLs_L6m_of_L12m   8.286667
6                pct_closed_tl   8.222912
24             num_deliq_12mts   8.148856
3            Tot_TL_closed_L6M   7.979556
22        num_times_delinquent   7.954229
39               num_lss_12mts   7.949944
9             pct_tl_open_L12M   7.818712
4              pct_tl_open_L6M   7.774982
35                num_dbt_6mts   7.383621
28                     num_std   7.229519
25           num_deliq_6_12mts   6.903433
38                num_lss_6mts   6.355318
10          pct_tl_closed_L12M   6.044483
23   max_recent_level_of_deliq   5.400825
19               Age_Oldest_TL   4.958184
40       recent_level_of_deliq   4.934841
5            pct_tl_closed_L6M   4.780838
15                     Home_TL   4.458920
54                     GL_Flag   4.404097
0                   PROSPECTID   3.998339
44         Time_With_Curr_Empr   3.938891
16                       PL_TL   3.582698
12                       CC_TL   3.379408
20               Age_Newest_TL   3.179288
33               num_sub_12mts   3.106482
47                     CC_Flag   3.090118

In [74]:
# check Anova for columns_to_be_kept 

#check annova to test colinearity when output column is categorical
from scipy.stats import f_oneway

columns_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])  
    b = list(df['Approved_Flag'])  
    
    group_P1 = [value for value, group in zip(a, b) if group == 'P1']
    group_P2 = [value for value, group in zip(a, b) if group == 'P2']
    group_P3 = [value for value, group in zip(a, b) if group == 'P3']
    group_P4 = [value for value, group in zip(a, b) if group == 'P4']


    f_statistic, p_value = f_oneway(group_P1, group_P2, group_P3, group_P4)

    if p_value <= 0.05:
        columns_to_be_kept_numerical.append(i)

In [75]:
df=df[columns_to_be_kept_numerical+['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']+['Approved_Flag']]
df.head()

,PROSPECTID,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_closed_L6M,pct_closed_tl,pct_tl_open_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6_12mts,num_times_60p_dpd,num_std,num_std_6mts,num_sub,num_sub_12mts,num_dbt,num_lss,recent_level_of_deliq,time_since_recent_enq,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_opened_TLs_L6m_of_L12m,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2,Approved_Flag
0,1,0,0,0.0,0.800,0.00,0.0,0,0,0,1,0,4,0,72,18,549,11,29,0,0,21,5,0,0,0,0,29,566,51000,114,0.0,0,1,0.0,0.0,1,0,Married,12TH,M,PL,PL,P2
1,2,0,0,0.0,0.000,1.00,0.0,0,0,1,0,0,0,0,7,7,47,0,0,0,0,0,0,0,0,0,0,0,209,19000,50,0.0,0,0,0.0,0.0,0,0,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan,P2
2,3,1,0,0.0,0.000,0.25,0.0,1,0,6,1,0,0,0,47,2,302,9,25,8,0,10,5,0,0,0,0,25,587,18,191,0.5,0,0,0.0,0.0,1,0,Married,SSC,M,ConsumerLoan,others,P2
3,4,1,0,0.0,0.000,1.00,0.0,1,0,0,0,0,0,1,5,5,-99999,0,0,0,0,5,4,0,0,0,0,0,-99999,10000,246,1.0,0,0,0.0,0.0,0,0,Married,SSC,M,others,others,P2
4,5,0,0,0.0,0.667,0.00,0.0,0,0,0,0,0,0,2,131,32,583,0,0,0,0,53,4,0,0,0,0,0,3951,15000,75,0.0,0,0,0.0,0.0,0,0,Married,POST-GRADUATE,M,AL,AL,P1

In [76]:
from sklearn.compose import ColumnTransformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder

# Encode 'Approved_Flag' separately
label_encoder = LabelEncoder()
df['Approved_Flag'] = label_encoder.fit_transform(df['Approved_Flag'])  # ✅ Encode separately

# Define preprocessor
preprocessor = ColumnTransformer([
    ('ordinal', OrdinalEncoder(), ['EDUCATION']),  # ✅ Pass as a list
    ('onehot', OneHotEncoder(handle_unknown='ignore', drop='first'), 
     ['GENDER', 'last_prod_enq2', 'first_prod_enq2', 'MARITALSTATUS'])
], remainder='passthrough')  # Keep other columns as they are

In [77]:
transformed_data = preprocessor.fit_transform(df)

In [78]:
feature_names = preprocessor.get_feature_names_out()  # Get transformed feature names
df_transformed = pd.DataFrame(transformed_data, columns=feature_names)

In [79]:
df_transformed

,ordinal__EDUCATION,onehot__GENDER_M,onehot__last_prod_enq2_CC,onehot__last_prod_enq2_ConsumerLoan,onehot__last_prod_enq2_HL,onehot__last_prod_enq2_PL,onehot__last_prod_enq2_others,onehot__first_prod_enq2_CC,onehot__first_prod_enq2_ConsumerLoan,onehot__first_prod_enq2_HL,onehot__first_prod_enq2_PL,onehot__first_prod_enq2_others,onehot__MARITALSTATUS_Single,remainder__PROSPECTID,remainder__Total_TL_opened_L6M,remainder__Tot_TL_closed_L6M,remainder__pct_tl_closed_L6M,remainder__pct_closed_tl,remainder__pct_tl_open_L12M,remainder__pct_tl_closed_L12M,remainder__Tot_Missed_Pmnt,remainder__CC_TL,remainder__Consumer_TL,remainder__Gold_TL,remainder__Home_TL,remainder__PL_TL,remainder__Other_TL,remainder__Age_Oldest_TL,remainder__Age_Newest_TL,remainder__time_since_recent_payment,remainder__num_times_delinquent,remainder__max_recent_level_of_deliq,remainder__num_deliq_6_12mts,remainder__num_times_60p_dpd,remainder__num_std,remainder__num_std_6mts,remainder__num_sub,remainder__num_sub_12mts,remainder__num_dbt,remainder__num_lss,remainder__recent_level_of_deliq,remainder__time_since_recent_enq,remainder__NETMONTHLYINCOME,remainder__Time_With_Curr_Empr,remainder__pct_opened_TLs_L6m_of_L12m,remainder__CC_Flag,remainder__PL_Flag,remainder__pct_PL_enq_L6m_of_ever,remainder__pct_CC_enq_L6m_of_ever,remainder__HL_Flag,remainder__GL_Flag,remainder__Approved_Flag
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.00,0.800,0.000,0.00,0.0,0.0,0.0,1.0,0.0,4.0,0.0,72.0,18.0,549.0,11.0,29.0,0.0,0.0,21.0,5.0,0.0,0.0,0.0,0.0,29.0,566.0,51000.0,114.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.00,0.000,1.000,0.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,7.0,7.0,47.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,209.0,19000.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,1.0,0.0,0.00,0.000,0.250,0.00,1.0,0.0,6.0,1.0,0.0,0.0,0.0,47.0,2.0,302.0,9.0,25.0,8.0,0.0,10.0,5.0,0.0,0.0,0.0,0.0,25.0,587.0,18.0,191.0,0.5,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,5.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,1.0,0.0,0.00,0.000,1.000,0.00,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,5.0,-99999.0,0.0,0.0,0.0,0.0,5.0,4.0,0.0,0.0,0.0,0.0,0.0,-99999.0,10000.0,246.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.00,0.667,0.000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,2.0,131.0,32.0,583.0,0.0,0.0,0.0,0.0,53.0,4.0,0.0,0.0,0.0,0.0,0.0,3951.0,15000.0,75.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51291,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,51332.0,1.0,0.0,0.00,0.000,0.333,0.00,0.0,0.0,2.0,0.0,0.0,0.0,1.0,24.0,5.0,15.0,2.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,18500.0,249.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
51292,5.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,51333.0,0.0,1.0,0.25,0.500,0.500,0.25,0.0,0.0,2.0,0.0,0.0,0.0,0.0,74.0,7.0,57.0,0.0,0.0,0.0,0.0,6.0,4.0,0.0,0.0,0.0,0.0,0.0,203.0,25000.0,186.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51293,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,51334.0,1.0,1.0,0.50,0.500,1.000,0.50,0.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,5.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,18000.0,66.0,0.5,0.0,0.0,1.0,0.0,0.0,0.0,2.0
51294,6.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,51335.0,0.0,0.0,0.00,0.500,0.500,0.50,0.0,0.0,2.0,0.0,0.0,0.0,0.0,15.0,8.0,58.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,242.0,12802.0,54.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
51295,5.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,51336.0,0.0,0.0,0.00,0.000,0.000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,20.0,74.0,0.0,0.0,0.0,0.0,18.0,4.0,0.0,0.0,0.0,0.0,0.0,13.0,16000.0,102.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [80]:
df_transformed.shape

(51296, 52)

In [81]:
df_transformed.columns

Index(['ordinal__EDUCATION', 'onehot__GENDER_M', 'onehot__last_prod_enq2_CC',
       'onehot__last_prod_enq2_ConsumerLoan', 'onehot__last_prod_enq2_HL',
       'onehot__last_prod_enq2_PL', 'onehot__last_prod_enq2_others',
       'onehot__first_prod_enq2_CC', 'onehot__first_prod_enq2_ConsumerLoan',
       'onehot__first_prod_enq2_HL', 'onehot__first_prod_enq2_PL',
       'onehot__first_prod_enq2_others', 'onehot__MARITALSTATUS_Single',
       'remainder__PROSPECTID', 'remainder__Total_TL_opened_L6M',
       'remainder__Tot_TL_closed_L6M', 'remainder__pct_tl_closed_L6M',
       'remainder__pct_closed_tl', 'remainder__pct_tl_open_L12M',
       'remainder__pct_tl_closed_L12M', 'remainder__Tot_Missed_Pmnt',
       'remainder__CC_TL', 'remainder__Consumer_TL', 'remainder__Gold_TL',
       'remainder__Home_TL', 'remainder__PL_TL', 'remainder__Other_TL',
       'remainder__Age_Oldest_TL', 'remainder__Age_Newest_TL',
       'remainder__time_since_recent_payment',
       'remainder__num_times_delinquent',
       'remainder__max_recent_level_of_deliq', 'remainder__num_deliq_6_12mts',
       'remainder__num_times_60p_dpd', 'remainder__num_std',
       'remainder__num_std_6mts', 'remainder__num_sub',
       'remainder__num_sub_12mts', 'remainder__num_dbt', 'remainder__num_lss',
       'remainder__recent_level_of_deliq', 'remainder__time_since_recent_enq',
       'remainder__NETMONTHLYINCOME', 'remainder__Time_With_Curr_Empr',
       'remainder__pct_opened_TLs_L6m_of_L12m', 'remainder__CC_Flag',
       'remainder__PL_Flag', 'remainder__pct_PL_enq_L6m_of_ever',
       'remainder__pct_CC_enq_L6m_of_ever', 'remainder__HL_Flag',
       'remainder__GL_Flag', 'remainder__Approved_Flag'],
      dtype='object')

In [82]:
X = df_transformed.drop(columns=['remainder__Approved_Flag']) 
y = df_transformed['remainder__Approved_Flag']

In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((41036, 51), (10260, 51), (41036,), (10260,))

In [84]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

In [85]:
# Apply Min-Max Scaling
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [86]:
models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42),
    "Naive Bayes": GaussianNB()
}

In [87]:
accuracy_scores = {}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)  # Train the model
    y_pred = model.predict(X_test_scaled)  # Predict on test data
    accuracy = accuracy_score(y_test, y_pred)  # Calculate accuracy
    accuracy_scores[name] = accuracy

c:\Users\my msi\anaconda3\envs\credit_lending_risk_analysis\Lib\site-packages\xgboost\training.py:183: UserWarning: [23:27:00] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [88]:
# Convert accuracy scores to DataFrame
accuracy_df = pd.DataFrame.from_dict(accuracy_scores, orient='index', columns=['Accuracy'])
accuracy_df.sort_values(by='Accuracy', ascending=False)

               Accuracy
XGBoost        0.757895
Random Forest  0.756823
Decision Tree  0.669006
Naive Bayes    0.537037